### ISSUE TITLE
`parentView.animate(view: self, isFullScreen: isFullScreen)` について

### ISSUE THREAD

**Issue by el-hoshino** [Timai-A2L/DoujinStock#1]
@Timai-A2L こちらのメソッドの呼び出しがあるけど、定義ってどこにあるんです？

**Comment by Timai-A2L** [comment]
定義はSwitcherViewにあります。
Appleのサンプルからそのまま引っ張ってきているので正しいかどうかは分かりませんが、おそらく画面の変形を制御しているのがSwitcherViewの方になるので、メソッドをこちらに記述していると思われます。ContainerViewはあくまでコンテンツの表示のためのViewだと思っています。

**Comment by el-hoshino** [comment]
とのことですが、`SwitcherView`に定義見当たらないですね

`standardInitialize()`
`radians(degree:)`
`getTransform(translatedToX:isScale:isRotate)`

の定義しか見当たらない

**Comment by Timai-A2L** [comment]
チェックしました。
どうやら、当方のcommitミスです。stageに上げずcommitしてました。
ファイルを修正しました。

**Comment by el-hoshino** [comment]
LGTM
